service:
  name: one-two-step-function

custom:
  retryStep:
    - ErrorEquals:
      - States.ALL
      IntervalSeconds: 5
      MaxAttempts: 2
      BackoffRate: 2
  catchStep:
    - ErrorEquals:
      - States.ALL
      ResultPath: "$.errorInfo"
      Next: SendErrorQueueState

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  stage: ${opt:stage, self:custom.default_stage}
  stackName: ${self:service.name}-${opt:stage, self:custom.default_stage}
  versionFunctions: false

  environment:
    region: ${self:provider.region}
    stage: ${self:provider.stage}
    stackName: ${self:service.name}-${opt:stage, 'dev'}
    ORDER_TABLE_NAME: order-${self:provider.stage}-table

  iamRoleStatements:
    - Effect: 'Allow'
      Action: "*"
      Resource: "*"


functions:
  - ${file(resources/functions.yml)}

stepFunctions:
  stateMachines: ${file(resources/stateMachines.yml)}

resources:
  - ${file(resources/resources.yml)}

plugins:
  - serverless-step-functions
